// <auto-generated />
namespace ClaimSystem.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class friday : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(friday));
        
        string IMigrationMetadata.Id
        {
            get { return "201911081505388_friday"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
